# Task.
\This is a realinterview task!  
We’vemet binary maze problem. Can you generalize it from binary maze to normal maze? Except for thechanging from binary maze to a normal maze, allother conditions remain the same. Your taskis still tofind out the shortest path from a start point to an end point. You can assume all input is valid.
![avatar](./binary_maze.png)

## find a short path in a binary maze

In [1]:
import numpy as np
import matplotlib.pyplot as plt


%matplotlib inline

In [2]:
class Node:
    def __init__(self, pos, state):
        self.pos = pos  # position
        self.state = state


class BaseMaze:
    def __init__(self, random_maze=False, maze_graphic=None):
        print(maze_graphic)
        if random_maze:
            maze = np.random.randint(low=0, high=2, size=(50, 50))
            self.maze = self.create_maze(maze_graphic)
        else:
            self.maze = self.create_maze(maze_graphic)
    
    
    def create_maze(self, maze):
        rows, cols = maze.shape
        result = np.zeros((rows, cols), dtype=Node)
        
        for i, row in enumerate(maze):
            for j, col in enumerate(maze[i]):
                result[i][j] = Node(str(i) + str(j), col)
        
        return result
    
    
    def visualize(self, solution=0):
        pass
    
    
    def search_around(self, current_node):
        row, col = int(current_node.pos[0]), int(current_node.pos[1])
        rows, cols = self.maze.shape[0]-1, self.maze.shape[1]-1
        around_nodes = {}
        
        # 解决在四个角落的问题
        if row in [0, rows] and col in [0, cols]:
            if row == 0:
                around_nodes['down'] = self.maze[row+1][col]
            else:
                around_nodes['up'] = self.maze[row-1][col]
            if col == 0:
                around_nodes['right'] = self.maze[row][col+1]
            else:
                around_nodes['left'] = self.maze[row][col-1]
                
        if around_nodes:
            return around_nodes
            
        # 解决在边线却不在角落的问题
        if row in [0, rows]:
            if row == 0:
                around_nodes['down'] = self.maze[row+1][col]
            elif row == rows:
                around_nodes['up'] = self.maze[row-1][col]
            around_nodes['left'] = self.maze[row][col-1]
            around_nodes['right'] = self.maze[row][col+1]
                
        if col in [0, cols]:
            if col == 0:
                around_nodes['right'] = self.maze[row][col+1]
            elif col == cols:
                around_nodes['left'] = self.maze[row][col-1]
            around_nodes['up'] = self.maze[row-1][col]
            around_nodes['down'] = self.maze[row+1][col]
        
        if around_nodes:
            return around_nodes

        # 解决即不在边线也不在角落的问题
        if row not in [0, rows] and col not in [0, cols]:
            around_nodes['left'] = self.maze[row][col-1]
            around_nodes['right'] = self.maze[row][col+1]
            around_nodes['up'] = self.maze[row-1][col]
            around_nodes['down'] = self.maze[row+1][col]

        return around_nodes

In [3]:
class BinaryMaze(BaseMaze):
    def __init__(self, random_maze=False, maze=None):
#         super().__init__(random_maze, maze)
        super(BinaryMaze, self).__init__(random_maze=random_maze, maze_graphic=maze)
        
    def visualize(self, solution=0):
        '''
        @vis_n: 0 visualize maze
                1 visualize BFS  (to do)
                2 visualize DFS  (to do)
        '''
        if solution == 0:
            print('maze size:', self.maze.shape)
            print('='*30, 'position', '='*30)
            for row in range(self.maze.shape[0]):
                for col in range(self.maze.shape[1]):
                    print(self.maze[row, col].pos, end='\t')
                print()
            print('='*30, 'state', '='*30)
            for row in range(self.maze.shape[0]):
                for col in range(self.maze.shape[1]):
                    print(self.maze[row, col].state, end='\t')
                print()
    
    
    def BFS_solution(self, start, destination):
        '''
        @start  string  eg: 13    the begining position
        @destination string  eg: 45  the ending position
        '''
        maze = self.maze
        start_i, start_j = int(start[0]), int(start[1])
        dest_i, dest_j = int(destination[0]), int(destination[1])
        dest_node = maze[dest_i, dest_j]
        pathes = [[maze[start_i, start_j]]]
        seen = set()
        
        
        while pathes:
            path = pathes.pop(0)
            froniter = path[-1]
            
            if froniter in seen:
                continue
            
            around_nodes = self.search_around(froniter)
            successors = [node for _, node in around_nodes.items()
                                    if node not in seen and node.state == 0 ]
            
            if not successors:
                raise '未找到目标值'
            
            for node in successors:
                print('standing at %s looking at %s' % (froniter.pos, node.pos))
                if node == dest_node:
                    return path + [node]
                else:
                    pathes.append(path + [node])
            print()
            seen.add(froniter)
                
                
    def DFS_solution(self, start, destination):
        maze = self.maze
        
        dest_i, dest_j = int(destination[0]), int(destination[1])
        dest_node = maze[dest_i, dest_j]
        
        start_i, start_j = int(start[0]), int(start[1])
        pathes = [maze[start_i, start_j], ]
        seen = set()
        path = [pathes[0].pos]
        
        while pathes:
            froniter = pathes.pop(0)
            
            if froniter == dest_node: return path
            
            around_nodes = self.search_around(froniter)
            
            successors = [node for _, node in around_nodes.items()
                              if node not in seen and  node.state == 0]
            
            
            for node in successors:
                path.append(node.pos)
                print('standing at {} looking at: {}'.format(froniter.pos, node.pos))
                if node == dest_node: return
            print()
            pathes += successors
            
            seen.add(froniter)

In [5]:
# test BinaryMaze
maze = np.array([[1, 0, 1, 1, 1],
                 [1, 0, 0, 0, 1],
                 [1, 0, 1, 0, 1],
                 [1, 0, 0, 0, 1],
                 [1, 0, 1, 1, 1]])

binary_maze = BinaryMaze(random_maze=False, maze=maze)
binary_maze.visualize()

# check: DFS 和 BFS 一样？
print('-'*20, 'DFS', '-'*20)
shortest_path = binary_maze.DFS_solution('01', '41')
print('-'*20, 'BFS', '-'*20)
shortest_path = binary_maze.BFS_solution('01', '41')
# print(shortest_path)

[[1 0 1 1 1]
 [1 0 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 0 1 1 1]]
maze size: (5, 5)
============================== position ==============================
00	01	02	03	04	
10	11	12	13	14	
20	21	22	23	24	
30	31	32	33	34	
40	41	42	43	44	
============================== state ==============================
1	0	1	1	1	
1	0	0	0	1	
1	0	1	0	1	
1	0	0	0	1	
1	0	1	1	1	
-------------------- DFS --------------------
standing at 01 looking at: 11

standing at 11 looking at: 12
standing at 11 looking at: 21

standing at 12 looking at: 13

standing at 21 looking at: 31

standing at 13 looking at: 23

standing at 31 looking at: 32
standing at 31 looking at: 41
-------------------- BFS --------------------
standing at 01 looking at 11

standing at 11 looking at 12
standing at 11 looking at 21

standing at 12 looking at 13

standing at 21 looking at 31

standing at 13 looking at 23

standing at 31 looking at 32
standing at 31 looking at 41


## Normal maze

## generalization task: find a short path in a normal maze

In [10]:
NORMAL_MAZE =  [[1, 5, 5, 5, 5],
                [1, 0, 0, 0, 1],
                [1, 1, 1, 1, 1],
                [3, 0, 0, 0, 1],
                [3, 3, 3, 3, 1]]

src = (0, 0)
dst = (4, 4)

In [23]:
class NormalMaze:
    def __init__(self, maze, source, destination):
        self.maze = maze
        self.source = source
        self.destination = destination
        self.solution = self.normal_solver(self.maze, self.source, self.destination)
        
    def cal_cost(self, path):
        cost = 0
        for _ in path:
            cost += 1
        
        return cost
    
    def normal_solver(self, maze, source, destination):
        # if illegal
        if not maze or not maze[0]:
            return "invalid maze"
        if maze[source[0]][source[1]] == 0 and maze[destination[0]][destination[1]] == 0:
            return 'invalid path'
        if source == destination:
            return 0, [source]
        
        max_r = len(maze) - 1
        max_b = len(maze[0]) - 1
        movements = [(1, 0), (-1, 0), (0, 1), (0, -1)]
        
        queue = [[source]]
        searched = {source}
        
        while queue:
            path = queue.pop(0)
            r, c = path[-1]
            
            if (r, c) == destination:
                return self.cal_cost(path), '->'.join(map(str, path))
                
            for dr, dc in movements:
                # 考虑边界问题 和 合法性问题
                if  0 <= (c + dc) <= max_r and 0 <= (r + dr) <= max_b and \
                    (r+dr, c+dc) not in searched and maze[r+dr][c+dc] != 0:
                        
                    queue.append(path + [(r+dr, c+dc)])
                    searched.add((r+dr, c+dc))
                    queue.sort(key=self.cal_cost)
                    
        return 'not path found'

In [25]:
normal_maze = NormalMaze(NORMAL_MAZE, src, dst)
normal_maze.solution

(9, '(0, 0)->(1, 0)->(2, 0)->(3, 0)->(4, 0)->(4, 1)->(4, 2)->(4, 3)->(4, 4)')

## To Do: Coding by C++.

# Task

What you are given is a sentence like:
“”
I am happy and sad
Please forget about how insane it is, just focusing on the following questions.
And then some substitutes of some words are provided as well:
{ {"happy", "glad"}, {"glad", "good"}, {"sad", "sorrow"} }
which means happy can be replaced by glad while glad can continuously substituted by good and so on.
Now, please write out all possible sentences with all substitutes. For example, by giving this specific case, your output should be like:
    
![avatar](./task02.bmp)  

Tips:This is really a complex problem. What it tests are:
0.For C++ player, how to separate string into words
1. How to build graph for our substitution?
2. How to get all substitution for all words? It’s actually a Cartesian Product, which can be completed by DFS
.
3. How to make sentences correctly?

In [233]:
corpus = [{'glad', 'happy', 'good'}, {'sad', 'sorrow'}]
sentence = 'I am happy and sad'
words = set(sentence.split(' '))

replaced_words = []
for _, c in enumerate(corpus):
    same_word = c & words
    if same_word:
        same_word = [s for s in same_word][0]
        replaced_words.append((same_word, list(c)))
        

def substitude_words(list_sen, replaced_words):
    if len(replaced_words) == 0:
        return list_sen
    
    replaced_word, words = replaced_words.pop(0)
#     print(replaced_word, words)

    result = []
    for sen in list_sen:
        for word in words:
            sen = sen.replace(replaced_word, word)
            replaced_word = word
            result.append(sen)

    list_sen += result
    list_sen = list(set(list_sen))
    
    return substitude_words(list_sen, replaced_words)

    1. How to build graph for our substitution?

In [231]:
import pandas as pd

In [249]:
categories = ('positive', 'negative')

data= {}
max_len = 0
for cate, words in zip(categories, replaced_words):
    data[cate] = [words[0]]
    for word in words[1]:
        data[cate].append(word)
    data[cate] = list(set(data[cate]))
    if len(data[cate]) > max_len:
        max_len = len(data[cate])

for cate in data:
    if len(data[cate]) < max_len:
        for i in range(len(data), max_len):
            data[cate].append(np.NaN)
    
data = pd.DataFrame(data=data, )
data

negative positive
0   sorrow     glad
1      sad    happy
2      NaN     good

In [274]:
replaced_sentences = [sentence]

sens = substitude_words(replaced_sentences, replaced_words)

for sen in sens:
    print(sen)

I am happy and sad


    2. How to get all substitution for all words? It’s actually a Cartesian Product, which can be completed by DFS .
Sorry, I can't.

    3. How to make sentences correctly?

In [26]:
corrected_words = {}

for sen in sens:
    words = sen.split(' ')
    print(words.index('and'))
    try:
        and_pos = words.index('and')
        previous = words[and_pos-1]
        _next = words[and_pos+1]
        for cate in data:
            if previous in list(data[cate]):
                cate1 = cate
            if _next in list(data[cate]):
                cate2 = cate
        
        if cate1 == cate2:
            print('Sentence is not needed to be corrected.')
        else:
            '''To do: 需要判断整个句子的情感来进行选择合适替换词'''
            substitutions = [w for w in data[cate1] if w != previous]
            words[and_pos+1] = substitutions[-1]
            new_sen = ' '.join(words)
            print(new_sen)
    except Exception:
        print('Correcting sentence is failure.')

NameError: name 'sens' is not defined

## build graph

In [7]:
sentence = "I am happy and sad."
substituted_list = [['happy', 'glad'], ['glad', 'good'], ['glad', 'great'], ['sad', 'sorrow']]

In [8]:
def build_graph(substituted_list):
    graph = {}
    
    for start, end in substituted_list:
        if start not in graph:
            graph[start] = [end]
        else:
            graph[start].append(end)
    
    return graph

In [9]:
graph = build_graph(substituted_list)

In [10]:
def dfs(graph, root):
    queue = [[root]]
    
    searched = {root}
    results = set()
    
    while queue:
        path = queue.pop()
        node = path[-1]
        searched.add(node)
        
        if node in graph:
            for des in graph[node]:
                queue.append(path + [des])
        else:
#             print(results, path)
            results = results | set(path)
        
    return list(results)

In [11]:
dfs(graph, 'happy')

['great', 'good', 'happy', 'glad']

In [12]:
dfs(graph, 'sad')

['sorrow', 'sad']

In [13]:
def cartesian_join(set_list):
    # [['I'], ['am'], ['happy', 'glad', 'good', 'great'], ['and'], ['sad.']]
    def dfs1(curr_list, set_idx):
        if set_idx == len(curr_list):
            word = curr_list
            res.append(word)
        for v in curr_list:
            res.append(res + [v], set_idx + 1)
    
    res = []
    dfs1([], 0)
    return res

def sentences_combination(sentence, substituted_list):
    words = sentence.split()
    
    graph = build_graph(substituted_list)
    product_list = [dfs(word) for word in words]
    sentences = [w for w in words if cartesian_join(w)]
    
    return sentences

In [14]:
def cartesian_product(setList):
    def dfs1(curr_list, set_idx):
        if set_idx == len(setList):
            res.append(curr_list)
            return
        for v in setList[set_idx]:
            dfs1(curr_list+[v], set_idx+1)
    res = []
    dfs1([], 0)
    return res

In [15]:
def sentences_combination(sentence, substitute_list):
    sentence_split = sentence.split(' ')
    graph = build_graph(substitute_list)
    product_list = [dfs(graph, word) for word in sentence_split]
    print('product_list', product_list)
    results = [' '.join(split_sentences) for split_sentences in cartesian_product(product_list)]
    return results

In [16]:
sentences_combination(sentence, substituted_list)

product_list [['I'], ['am'], ['great', 'good', 'happy', 'glad'], ['and'], ['sad.']]


['I am great and sad.',
 'I am good and sad.',
 'I am happy and sad.',
 'I am glad and sad.']

## To Do: Coding by C++.